version: "3"
services:
  crm-app:
    image: djcrm:1
    container_name: crm-app
    entrypoint: [] # Override the entrypoint
    command: bash -c "sleep 10 && cd /app && python3 manage.py collectstatic --noinput && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DBNAME=postgres
      - DBUSER=postgres
      - DBPASSWORD=0000
      - DBHOST=crm-db
      - DBPORT=5432

    depends_on:
      - crm-db
    ports:
      - 8000:8000
    networks:
      - nw

  crm-db:
    image: postgres:latest
    container_name: crm-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
    ports:
      - 5432:5432
    volumes:
      - /var/run/postgresql/:/var/run/postgresql
    networks:
      - nw

networks:
  nw: {}
